name: Hexo 部署

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: 检查源码
        uses: actions/checkout@v2
        with:
          ref: master

      - name: 安装 Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: 设置 Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "e-mmal@live.com"
          git config --global user.name "timibox"
          npm install hexo-cli -g
          npm install

      - name: 部署
        run: |
          hexo clean
          hexo deploy
